#!/usr/bin/env node
// node build.mjs           regenerate src/figures/index.js, dist/, registry/
// node build.mjs --check   fail if any generated file is out of date (CI)
import { build } from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const check = process.argv.includes("--check");
const at = (...p) => path.join(root, ...p);
const stale = [];
const write = (file, text) => {
  const prev = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (prev === text) return;
  if (check) { stale.push(path.relative(root, file)); return; }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  console.log("wrote", path.relative(root, file));
};

// 1 · figure index — one named export per file in src/figures
const names = fs.readdirSync(at("src/figures")).filter((f) => f.endsWith(".js") && f !== "index.js").map((f) => f.slice(0, -3)).sort();
const camel = (n) => n.replace(/-(\w)/g, (_, c) => c.toUpperCase());
write(at("src/figures/index.js"),
  "// Generated by build.mjs — one export per figure file. Do not edit.\n" +
  names.map((n) => `export { default as ${camel(n)} } from "./${n}.js";`).join("\n") + "\n");

write(at("src/figures/index.d.ts"),
  "// Generated by build.mjs. Do not edit.\nimport type { Figure } from \"../figure\";\n" +
  names.map((n) => `export declare const ${camel(n)}: Figure;`).join("\n") + "\n");

// 2 · browser bundle: window.Bitlight with every figure registered
const bundle = await build({
  entryPoints: [at("src/global.js")], bundle: true, format: "iife", target: "es2020",
  minify: true, write: false, legalComments: "none",
  banner: { js: `/*! bitlight ${JSON.parse(fs.readFileSync(at("package.json"))).version} · MIT */` },
});
write(at("dist/bitlight.global.js"), bundle.outputFiles[0].text);

// 3 · shadcn registry item: the library files, so `npx shadcn add <url>` vendors them
const files = ["core.js", "props.js", "bitlight.js", "react.js", "figures/index.js", ...names.map((n) => `figures/${n}.js`)];
const registry = {
  $schema: "https://ui.shadcn.com/schema/registry-item.json",
  name: "bitlight",
  type: "registry:lib",
  title: "Bitlight",
  description: "Objects drawn in one bit, lit by your pointer.",
  dependencies: [],
  files: files.map((f) => ({ path: `lib/bitlight/${f}`, type: "registry:lib", content: fs.readFileSync(at("src", f), "utf8") })),
};
write(at("registry/bitlight.json"), JSON.stringify(registry, null, 2) + "\n");

if (check && stale.length) { console.error("out of date — run `node build.mjs`:\n  " + stale.join("\n  ")); process.exit(1); }
if (check) console.log("build: up to date");
