/*
 * Bitlight — objects drawn in one bit, lit by your pointer.
 *
 * A figure is a still object on a plate, ray-marched once and cached. The
 * pointer is a lamp hovering over the plate; every frame re-lights the cached
 * surface (core.shade) and orders it into two inks (core.dither).
 *
 *   define({ name, means, sdf, bound, rest, albedo?, plateTone?, view?, read? })
 *     sdf(x, y, z)      signed distance to the object (the plate is added for you)
 *     bound             [x, y, z, r] sphere enclosing the object (shadow culling)
 *     rest              [x, y, z] lamp position at rest — this frame is the thumbnail
 *     albedo(x, y, z)   0–1 object tone (default 0.92); plateTone likewise (0.86)
 *     view              { half, lift, yaw, pitch, plate, cols, rows, lampY }
 *     read(lamp)        caption text; default "az 214° · el 38°"
 *   mount(host, figure | name, { cell, theme, label, onRead }) → handle
 *
 * Do not edit this file or core.js to make one figure work. If a figure needs
 * something the kernel does not offer, the figure is the wrong shape.
 */
import { LOOK, BAYER, sd, shade, dither, occlusion, normal, camera, march, lampAngles } from "./core.js";

export { LOOK, BAYER, sd };

const max = Math.max, min = Math.min, abs = Math.abs, sqrt = Math.sqrt;

// ---------- registry ----------
export const figures = new Map();
export function define(def) {
  for (const key of ["name", "means", "sdf", "bound", "rest"])
    if (def[key] == null) throw new Error(`Bitlight.define: "${key}" is required`);
  figures.set(def.name.toLowerCase(), def);
  return def;
}

// ---------- shared clock ----------
// One requestAnimationFrame for the whole page. Off-screen or settled figures
// leave `awake`, and the loop stops when `awake` is empty (rules · 09 Cost).
const awake = new Set();
let raf = 0, last = 0;
function wake(fig) {
  awake.add(fig);
  if (!raf) { last = performance.now(); raf = requestAnimationFrame(loop); }
}
function loop(now) {
  const dt = Math.min(0.05, (now - last) / 1000);
  last = now;
  for (const fig of awake) if (!fig.tick(dt)) awake.delete(fig);
  raf = awake.size ? requestAnimationFrame(loop) : 0;
}

const media = (q) => (typeof matchMedia === "function" ? matchMedia(q) : null);

function parseColor(str, fallback) {
  const probe = document.createElement("canvas").getContext("2d");
  probe.fillStyle = fallback;
  probe.fillStyle = (str || "").trim() || fallback;
  probe.fillRect(0, 0, 1, 1);
  const d = probe.getImageData(0, 0, 1, 1).data;
  return [d[0], d[1], d[2]];
}

export const defaultRead = (L) => {
  const { az, el } = lampAngles([L.x, L.y, L.z]);
  return `az ${String(az).padStart(3, "0")}° · el ${el}°`;
};

// ---------- mount ----------
export function mount(host, figure, opts = {}) {
  const def = typeof figure === "string" ? figures.get(figure.toLowerCase()) : figure;
  if (!def) throw new Error(`Bitlight: no figure called "${figure}"`);
  const reduceMotion = media("(prefers-reduced-motion: reduce)");
  const prefersDark = media("(prefers-color-scheme: dark)");

  const view = Object.assign({ half: 2.3, lift: 0.35, yaw: 45, pitch: 30, plate: 1.6, cols: 160, rows: 120 }, def.view);
  const cell = opts.cell || 3;
  const W = view.cols, H = view.rows, N = W * H;
  const { f, r, u } = camera(view.yaw, view.pitch);
  const unit = (2 * view.half) / W;
  const cx = -f[0] * 12, cy = -f[1] * 12 + view.lift, cz = -f[2] * 12;

  const P = view.plate, PT = 0.08;
  const plate = (x, y, z) => sd.box(x, y + PT, z, P, PT, P, 0.06);
  const object = def.sdf;
  const scene = (x, y, z) => min(plate(x, y, z), object(x, y, z));
  const albedo = def.albedo || (() => 0.92);
  const plateTone = def.plateTone || (() => 0.86);

  // ---- one-time march: geometry never moves, so cache the surface ----
  const kind = new Uint8Array(N); // 0 miss, 1 plate, 2 object
  const px = new Float32Array(N), py = new Float32Array(N), pz = new Float32Array(N);
  const nx = new Float32Array(N), ny = new Float32Array(N), nz = new Float32Array(N);
  const tone = new Float32Array(N), occl = new Float32Array(N), depth = new Float32Array(N).fill(1e9);
  const lum = new Float32Array(N), bits = new Uint8Array(N), n = [0, 0, 0];
  const t0 = performance.now();
  for (let j = 0, k = 0; j < H; j++) {
    for (let i = 0; i < W; i++, k++) {
      const sx = (i + 0.5 - W / 2) * unit, sy = -(j + 0.5 - H / 2) * unit;
      const ox = cx + r[0] * sx + u[0] * sy, oy = cy + u[1] * sy, oz = cz + r[2] * sx + u[2] * sy;
      const t = march(scene, ox, oy, oz, f[0], f[1], f[2], 30, 160);
      if (t < 0) continue;
      const x = ox + f[0] * t, y = oy + f[1] * t, z = oz + f[2] * t;
      normal(scene, x, y, z, n);
      const onObject = object(x, y, z) <= plate(x, y, z);
      kind[k] = onObject ? 2 : 1;
      depth[k] = t;
      px[k] = x; py[k] = y; pz[k] = z; nx[k] = n[0]; ny[k] = n[1]; nz[k] = n[2];
      tone[k] = onObject ? albedo(x, y, z) : plateTone(x, y, z);
      occl[k] = occlusion(scene, x, y, z, n[0], n[1], n[2]);
    }
  }
  const marchMs = performance.now() - t0;

  // ---- DOM ----
  const canvas = document.createElement("canvas");
  canvas.width = W; canvas.height = H;
  canvas.className = "bitlight-canvas";
  canvas.style.width = `${W * cell}px`;
  canvas.style.imageRendering = "pixelated";
  host.classList.add("bitlight");
  host.setAttribute("role", "img");
  if (!host.hasAttribute("tabindex")) host.setAttribute("tabindex", "0");
  host.setAttribute("aria-label", opts.label || `${def.name}. ${def.means}`);
  host.appendChild(canvas);
  const ctx = canvas.getContext("2d", { alpha: false });
  const img = ctx.createImageData(W, H);
  const buf32 = new Uint32Array(img.data.buffer);

  let litRGBA = 0, unlitRGBA = 0, ground = 1;
  const pack = ([R, G, B]) => ((255 << 24) | (B << 16) | (G << 8) | R) >>> 0; // little-endian RGBA
  function readTheme() {
    const theme = opts.theme || "auto";
    const dark = theme === "dark" || (theme === "auto" && !!prefersDark && prefersDark.matches);
    const cs = getComputedStyle(host);
    litRGBA = pack(parseColor(cs.getPropertyValue("--bitlight-lit"), dark ? "#d9dcd2" : "#e4e6df"));
    unlitRGBA = pack(parseColor(cs.getPropertyValue("--bitlight-unlit"), dark ? "#0e100e" : "#121411"));
    ground = dark ? 0 : 1; // paper ground in light theme, night ground in dark
  }
  readTheme();

  // ---- lamp ----
  const LAMP_Y = view.lampY || 1.5, REACH = P + 0.9;
  const rest = { x: def.rest[0], y: def.rest[1], z: def.rest[2] };
  const lamp = { ...rest }, goal = { ...rest }, vel = { x: 0, y: 0, z: 0 };
  const light = { p: [lamp.x, lamp.y, lamp.z] }, lights = [light];

  // screen (u, v in 0–1 over the canvas) → point on the lamp plane under it
  function unproject(uu, vv) {
    const sx = (uu * W - W / 2) * unit, sy = -(vv * H - H / 2) * unit;
    const ox = cx + r[0] * sx + u[0] * sy, oy = cy + u[1] * sy, oz = cz + r[2] * sx + u[2] * sy;
    const t = (LAMP_Y - oy) / f[1];
    let x = ox + f[0] * t, z = oz + f[2] * t;
    const d = Math.hypot(x, z);
    if (d > REACH) { x *= REACH / d; z *= REACH / d; } // rules · 03 Reach
    return { x, y: LAMP_Y, z };
  }

  let lastRead = "", lastMs = 0;
  const read = def.read || defaultRead;
  const mat = { a: 0.9, s: 0, e: 0 };

  function render() {
    const s = performance.now();
    light.p[0] = lamp.x; light.p[1] = lamp.y; light.p[2] = lamp.z;
    for (let k = 0; k < N; k++) {
      if (!kind[k]) { lum[k] = -1; continue; }
      mat.a = tone[k]; mat.s = kind[k] === 2 ? 1 : 0;
      lum[k] = shade(px[k], py[k], pz[k], nx[k], ny[k], nz[k], occl[k], mat, lights, LOOK.AMBIENT, f, object, def.bound);
    }
    dither(lum, depth, W, H, bits, W, 0, 0, ground);
    for (let k = 0; k < N; k++) buf32[k] = bits[k] ? litRGBA : unlitRGBA;
    ctx.putImageData(img, 0, 0);
    lastMs = performance.now() - s;
    const text = read(lamp);
    if (text !== lastRead) { lastRead = text; opts.onRead && opts.onRead(text); }
  }

  // ---- motion: a stiff spring follows, a soft one carries the lamp home (rules · 08) ----
  let visible = true, homing = false;
  const fig = {
    tick(dt) {
      if (!visible) return false;
      const k = homing ? 40 : 170, c = 2 * sqrt(k); // critically damped
      let moving = false;
      for (const a of ["x", "y", "z"]) {
        vel[a] += (k * (goal[a] - lamp[a]) - c * vel[a]) * dt;
        lamp[a] += vel[a] * dt;
        if (abs(goal[a] - lamp[a]) > 0.0015 || abs(vel[a]) > 0.003) moving = true;
        else { lamp[a] = goal[a]; vel[a] = 0; }
      }
      render();
      return moving;
    },
  };
  function aim(target, home) {
    homing = home;
    Object.assign(goal, target);
    if (reduceMotion && reduceMotion.matches) {
      Object.assign(lamp, target); vel.x = vel.y = vel.z = 0; render(); return;
    }
    wake(fig);
  }

  // ---- input: pointer, touch, keyboard ----
  let kbU = 0.5, kbV = 0.5;
  function onMove(e) {
    const b = canvas.getBoundingClientRect();
    kbU = (e.clientX - b.left) / b.width; kbV = (e.clientY - b.top) / b.height;
    aim(unproject(kbU, kbV), false);
  }
  const onLeave = () => aim(rest, true);
  function onKey(e) {
    const step = 0.06;
    if (e.key === "Escape") { onLeave(); return; }
    if (e.key === "ArrowLeft") kbU -= step; else if (e.key === "ArrowRight") kbU += step;
    else if (e.key === "ArrowUp") kbV -= step; else if (e.key === "ArrowDown") kbV += step;
    else return;
    e.preventDefault();
    kbU = max(0, min(1, kbU)); kbV = max(0, min(1, kbV));
    aim(unproject(kbU, kbV), false);
  }
  const events = [["pointermove", onMove], ["pointerdown", onMove], ["pointerleave", onLeave], ["keydown", onKey], ["blur", onLeave]];
  for (const [ev, fn] of events) host.addEventListener(ev, fn);

  const io = typeof IntersectionObserver === "function"
    ? new IntersectionObserver(([entry]) => { visible = entry.isIntersecting; if (visible) wake(fig); })
    : null;
  io && io.observe(host);
  const onScheme = () => { readTheme(); render(); };
  prefersDark && prefersDark.addEventListener("change", onScheme);

  render();

  return {
    name: def.name,
    means: def.means,
    /** Put the lamp under (u, v) — 0–1 across the canvas — at once. For tests and sheets. */
    lampAt(uu, vv) { Object.assign(lamp, unproject(uu, vv)); Object.assign(goal, lamp); render(); return lastRead; },
    /** Return the lamp to its designed rest position at once. */
    rest() { Object.assign(lamp, rest); Object.assign(goal, lamp); render(); return lastRead; },
    /** Re-read colours, e.g. after the page switched theme. */
    retheme(theme) { if (theme) opts.theme = theme; readTheme(); render(); },
    get stats() { return { marchMs, renderMs: lastMs, cols: W, rows: H, read: lastRead }; },
    destroy() {
      awake.delete(fig);
      io && io.disconnect();
      prefersDark && prefersDark.removeEventListener("change", onScheme);
      for (const [ev, fn] of events) host.removeEventListener(ev, fn);
      canvas.remove();
    },
  };
}
